version: '3.2'
services:
  java-build:
    environment:
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_COMMIT
      - GRADLE_USER_HOME=/.gradle
      - PUSH_RELEASE
      - BUILDKITE_JOB_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - CI=${BUILDKITE}
      - BUILD_NUMBER=${BUILDKITE_BUILD_NUMBER}
      - GIT_BRANCH=${BUILDKITE_BRANCH}
      - BUILD_VERSION=${BUILD_VERSION}
    image: openjdk:14-jdk
    working_dir: /app
    volumes:
      - ..:/app
      - /tmp/gradle-cache:/.gradle